### ISSUE TITLE
Content link in HW07 expired

### ISSUE THREAD

**Issue by pingfan-hu** [emse-eda-gwu/2023-Fall#2]
Hi professor, I found out that in **HW07 Section 2**, the heat map of "How common is your birthday" has link from [thedailyviz.com](https://thedailyviz.com), which has already retired, with all its webpages showing 404. I recommend that you change to some other heat map examples.

![Link Expired](https://github.com/emse-eda-gwu/2023-Fall/assets/84371500/3d5a6e9b-a9b6-45e1-85da-86bdcff5bb02)

**Comment by jhelvy** [comment]
thanks, fixed
